# Configuration Options
title: "E155 MicroPs Final Project: Rhythm Game"
author: "Julia Du and Allison Tsai"
theme: minima

header-pages:
  - mcu.html
  - fpga.html
  - results.html
  - documentation.html
  - about.html

# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: https://github.com/julia-du/Rhythm-Game
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
