# Configuration Options
title: "Rhythm Game"
author: "Julia Du and Allison Tsai"
theme: minima

header-pages:
  - 01_mcu
  - 02_fpga
  - 03_results
  - 04_documentation
  - 05_about

# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: https://github.com/julia-du/Rhythm-Game
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
